# Generated by Django 3.1.13 on 2021-09-04 09:31

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactpage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='banner_title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
