# Generated by Django 3.1.13 on 2021-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210904_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='banner_subtitle',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
