# Generated by Django 3.1.13 on 2021-09-04 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Help',
            new_name='HelpCenter',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
