# Generated by Django 3.1.13 on 2021-09-04 13:31

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0004_auto_20210904_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='body',
        ),
        migrations.AddField(
            model_name='faq',
            name='common_questions',
            field=wagtail.core.fields.StreamField([('question', wagtail.core.blocks.CharBlock(form_classname='Full Title')), ('Paragraph', wagtail.core.blocks.RichTextBlock())], null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
