# Generated by Django 3.1.13 on 2021-09-04 15:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0007_auto_20210904_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='common_questions',
            field=wagtail.core.fields.StreamField([('commonly_asked_questions', wagtail.core.blocks.StructBlock([('category', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('questions_and_answer', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('paragraph', wagtail.core.blocks.TextBlock(max_length=1000, required=True))])))])), ('add_form', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('body', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock()), ('form', wagtail.core.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.core.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))]))])))]))], null=True),
        ),
    ]
