EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'kuyesurogers81@gmail.com'
EMAIL_HOST_PASSWORD = 'vanjerry@81'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



RECAPTCHA_PUBLIC_KEY = "6LfOHrYbAAAAAFR8hGuSsSf9LKnoxOeHLgDn7MCF"
RECAPTCHA_PRIVATE_KEY = "6LfOHrYbAAAAAECNrzG1pBX7aaHH9cc5Ov6K1rXa"
NORECAPTCHA = True

